version: '3'
services:

    nginx:
        build:
            context: .docker/nginx/
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html

    php:
        build:
            context: .docker/php
        volumes:
            - .:/var/www/html

    mysql:
        build:
            context: .docker/mysql/
        volumes:
           - ./.docker/data/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: movie-app
            MYSQL_USER: movie_user
            MYSQL_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
#        container_name: sf4_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql

    composer:
        build:
            context: .docker/composer
        restart: 'no'
        command: install -d /var/www/html --ignore-platform-reqs
        volumes:
            - .:/var/www/html
        depends_on:
          - php
